### async & await

1. 会把返回值包装成 Promise 类型

2. await 
   1. 后面的代码 会自动被 Promise.resolve 转换
   2. 如果 await 后面的是原始类型 等同于 同步代码
   3. 只要一个await语句后面的 Promise 变为reject，那么整个async函数都会中断执行。自动抛出错误
      - 解决方案 try catch
      - then 添加 catch 回调
   4. 解决了回调地狱的问题

3. 当函数执行的时候，一旦遇到await就会先返回，等到异步操作完成，再接着执行函数体内后面的语句。
    从表面上解决了回调地狱的问题

4. 所有 await 命令后的 Promise 对象执行完成，
    遇到 return
    抛出错误
  也就是说，只有async函数内部的异步操作执行完，才会执行then方法指定的回调函数。

  await命令后面的 Promise 对象如果变为reject状态，则reject的参数会被catch方法的回调函数接收到。
  如果await语句前面没有return，但是reject方法的参数依然传入了catch方法的回调函数。
  这里如果在await前面加上return，效果是一样的。

  只要一个await语句后面的 Promise 变为reject，那么整个async函数都会中断执行。

  有时，我们希望即使前一个异步操作失败，也不要中断后面的异步操作。  
  ```js
  async function f() {
    await Promise.reject('出错了')
      .catch(e => console.log(e));
    return await Promise.resolve('hello world');
  }

  f() .then(v => console.log(v))
  // 出错了
  // hello world
  ```

### Promise
Promise 新建后就会立即执行。
```js
let promise = new Promise(function(resolve, reject) {
  console.log('Promise');
  resolve();
});

promise.then(function() {
  console.log('resolved.');
});

console.log('Hi!');
```
Promise 新建后 **立即执行**，所以首先输出的是Promise。
然后，then方法指定的回调函数，将在当前脚本 **所有同步任务执行完才会执行**，所以resolved最后输出。

Promise 对象抛出的错误不会传递到外层代码，即不会有任何反应。
会打印出错误提示ReferenceError: x is not defined，但是不会退出进程、终止脚本执行，2 秒之后还是会输出123。
这就是说，Promise 内部的错误不会影响到 Promise 外部的代码，通俗的说法就是 **Promise 会吃掉错误**

**每次 then，catch 返回的都是一个全新的 Promise 对象**

catch方法返回的还是一个 Promise 对象，因此后面还可以接着调用then方法。
```js
const someAsyncThing = function() {
  return new Promise(function(resolve, reject) {
    // 下面一行会报错，因为x没有声明
    resolve(x + 2);
  });
};

someAsyncThing()
.catch(function(error) {
  console.log('oh no', error);
})
.then(function() {
  console.log('carry on');
});
// oh no [ReferenceError: x is not defined]
// carry on
```

### Promise.prototype.finally()
1. 不接受任何参数
2. 总是会返回原来的值
finally方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。该方法是 ES2018 引入标准的。

finally方法的回调函数不接受任何参数，这意味着没有办法知道，前面的 Promise 状态到底是fulfilled还是rejected。
这表明，finally方法里面的操作，应该是与状态无关的，不依赖于 Promise 的执行结果。

finally方法总是会返回原来的值。

finally本质上是then方法的特例。

```js
Promise.prototype.finally = function (callback) {
  let P = this.constructor;
  return this.then(
    value  => P.resolve(callback()).then(() => value),
    reason => P.resolve(callback()).then(() => { throw reason })
  );
};
```

### Promise.all()
Promise.all方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。
只有实例的状态都变成fulfilled，或者其中有一个变为rejected，才会调用Promise.all方法后面的回调函数。 
```js
// 生成一个Promise对象的数组
const promises = [2, 3, 5, 7, 11, 13].map(function (id) {
  return getJSON('/post/' + id + ".json");
});

Promise.all(promises).then(function (posts) {
  // ...
}).catch(function(reason){
  // ...
});
```

### Promise.race()
Promise.race方法同样是将多个 Promise 实例，包装成一个新的 Promise 实例。
如果指定时间内没有获得结果，就将 Promise 的状态变为reject，否则变为resolve。
**hack Promise 运行时 不能停止的问题**
```js
const p = Promise.race([
  fetch('/resource-that-may-take-a-while'),
  new Promise(function (resolve, reject) {
    setTimeout(() => reject(new Error('request timeout')), 5000)
  })
]);

p
.then(console.log)
.catch(console.error);
```

### Promise.resolve() 
有时需要将现有对象转为 Promise 对象，Promise.resolve方法就起到这个作用。

```js
Promise.resolve('foo')
// 等价于
new Promise(resolve => resolve('foo'))
```

（1）参数是一个 Promise 实例，原封不动返回

（2）参数是一个thenable对象,Promise.resolve方法会将这个对象转为 Promise 对象，然后就立即执行thenable对象的then方法。
```js
let thenable = {
  then: function(resolve, reject) {
    resolve(42);
  }
};

let p1 = Promise.resolve(thenable);
p1.then(function(value) {
  console.log(value);  // 42
});
```

（3）参数不是具有then方法的对象，或根本就不是对象
如果参数是一个原始值，或者是一个不具有then方法的对象，则Promise.resolve方法返回一个新的 Promise 对象，状态为resolved。
```js
const p = Promise.resolve('Hello');

p.then(function (s){
  console.log(s)
});
// Hello
```

（4）不带有任何参数
Promise.resolve方法允许调用时不带参数，直接返回一个resolved状态的 Promise 对象。
需要注意的是，立即resolve的 Promise 对象，是在 **本轮“事件循环”（event loop）的结束时**，而不是在下一轮“事件循环”的开始时。
```js
setTimeout(function () {
  console.log('three');
}, 0);

Promise.resolve().then(function () {
  console.log('two');
});

console.log('one');

// one
// two
// three
```


### 应用
```js
const preloadImage = function (path) {
  return new Promise(function (resolve, reject) {
    const image = new Image();
    image.onload  = resolve;
    image.onerror = reject;
    image.src = path;
  });
};
```